
-- ============================================================
-- PROSPECT PULSE SEARCHER - COMPLETE SCHEMA
-- Run this ENTIRE file in Supabase SQL Editor
-- https://vpsnhpqtnjficdsrafrf.supabase.co
-- ============================================================

-- ============================================================
-- STEP 1: ENUMS
-- ============================================================

DO $$ BEGIN
  CREATE TYPE public.disposition_type AS ENUM (
    'not_interested', 'wrong_number', 'dnc', 'call_back_later', 'not_relevant',
    'others', 'not_connected', 'duplicate_prospect', 'irrelevant_company',
    'contact_details_irrelevant', 'not_interested_in_company',
    'reception_call_with_receptionist', 'hold_for_now', 'irrelevant_designation',
    'irrelevant_location', 'do_not_call', 'contract_renewal_year',
    'long_term_contract', 'no_requirements', 'call_back', 'follow_up',
    'mail_sent', 'meeting_scheduled', 'meeting_successful', 'meeting_cancel',
    'using_our_services', 'already_in_touch_with_team', 'person_irrelevant'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.sim_operator AS ENUM ('Airtel', 'Jio');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.sim_risk_level AS ENUM ('Normal', 'Warning', 'High Risk');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.sim_status AS ENUM ('Active', 'Spam', 'Deactivated', 'Inactive');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ============================================================
-- STEP 2: CORE TABLES
-- ============================================================

-- users (public profile, linked to auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text,
  role text NOT NULL DEFAULT 'caller',
  project_name text,
  status text DEFAULT 'active',
  last_active timestamptz
);

-- user_profiles
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  full_name text,
  role text DEFAULT 'caller',
  project text,
  last_login timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- prospects (main search table)
CREATE TABLE IF NOT EXISTS public.prospects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  company_name text NOT NULL DEFAULT '',
  prospect_email text,
  prospect_number text,
  prospect_number2 text,
  prospect_number3 text,
  prospect_number4 text,
  prospect_number5 text,
  prospect_linkedin text,
  prospect_city text,
  prospect_designation text,
  company_linkedin_url text
);

-- project_names
CREATE TABLE IF NOT EXISTS public.project_names (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz DEFAULT now()
);

-- projects
CREATE TABLE IF NOT EXISTS public.projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_id uuid NOT NULL REFERENCES public.users(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- project_users
CREATE TABLE IF NOT EXISTS public.project_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.projects(id),
  user_id uuid NOT NULL REFERENCES public.users(id),
  role text NOT NULL DEFAULT 'caller',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- master_prospects
CREATE TABLE IF NOT EXISTS public.master_prospects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  linkedin_id text NOT NULL UNIQUE,
  canonical_url text NOT NULL,
  full_name text,
  company_name text,
  prospect_designation text,
  prospect_city text,
  prospect_email text,
  prospect_number text,
  prospect_number2 text,
  prospect_number3 text,
  prospect_number4 text,
  row_number integer,
  verified boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- project_prospects
CREATE TABLE IF NOT EXISTS public.project_prospects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.projects(id),
  master_prospect_id uuid NOT NULL REFERENCES public.master_prospects(id),
  added_by uuid NOT NULL REFERENCES public.users(id),
  credit_allocated boolean NOT NULL DEFAULT false,
  credited_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- dispositions
CREATE TABLE IF NOT EXISTS public.dispositions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  prospect_id bigint NOT NULL REFERENCES public.prospects(id),
  user_id uuid NOT NULL REFERENCES public.users(id),
  user_name text,
  project_name text,
  disposition_type public.disposition_type NOT NULL,
  custom_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- activity_logs
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id),
  prospect_id bigint,
  action text,
  details jsonb,
  timestamp timestamptz DEFAULT now()
);

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.users(id),
  action text NOT NULL,
  target_table text,
  target_id text,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- exports
CREATE TABLE IF NOT EXISTS public.exports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id),
  prospect_ids bigint[],
  format text,
  timestamp timestamptz DEFAULT now()
);

-- notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users(id),
  type text NOT NULL,
  payload jsonb,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- credits_log
CREATE TABLE IF NOT EXISTS public.credits_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users(id),
  project_id uuid NOT NULL REFERENCES public.projects(id),
  master_prospect_id uuid NOT NULL REFERENCES public.master_prospects(id),
  action text NOT NULL,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- enrichment_jobs
CREATE TABLE IF NOT EXISTS public.enrichment_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  master_prospect_id uuid NOT NULL REFERENCES public.master_prospects(id),
  provider text,
  status text NOT NULL DEFAULT 'pending',
  result jsonb,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- lusha_api_keys
CREATE TABLE IF NOT EXISTS public.lusha_api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key_value text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  is_active boolean DEFAULT true,
  credits_remaining integer,
  last_used_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- rtne_requests
CREATE TABLE IF NOT EXISTS public.rtne_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_name text NOT NULL,
  project_name text NOT NULL,
  linkedin_url text NOT NULL,
  full_name text,
  company_name text,
  job_title text,
  city text,
  company_linkedin_url text,
  primary_phone text,
  phone2 text,
  phone3 text,
  phone4 text,
  email_address text,
  phone1_disposition text,
  phone1_disposition_at timestamptz,
  phone1_disposition_by text,
  phone2_disposition text,
  phone2_disposition_at timestamptz,
  phone2_disposition_by text,
  phone3_disposition text,
  phone3_disposition_at timestamptz,
  phone3_disposition_by text,
  phone4_disposition text,
  phone4_disposition_at timestamptz,
  phone4_disposition_by text,
  mre_requested boolean DEFAULT false,
  mre_requested_at timestamptz,
  mre_requested_by text,
  status text NOT NULL DEFAULT 'pending',
  row_number integer NOT NULL DEFAULT 1,
  completed_at timestamptz,
  completed_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- sim_agents
CREATE TABLE IF NOT EXISTS public.sim_agents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  project text,
  status text NOT NULL DEFAULT 'Active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- sim_master
CREATE TABLE IF NOT EXISTS public.sim_master (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sim_number text NOT NULL UNIQUE,
  operator public.sim_operator NOT NULL,
  current_status public.sim_status NOT NULL DEFAULT 'Active',
  risk_level public.sim_risk_level NOT NULL DEFAULT 'Normal',
  assigned_agent_id uuid REFERENCES public.sim_agents(id),
  project_name text,
  spam_count integer NOT NULL DEFAULT 0,
  last_spam_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- sim_spam_history
CREATE TABLE IF NOT EXISTS public.sim_spam_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sim_id uuid NOT NULL REFERENCES public.sim_master(id),
  agent_id uuid REFERENCES public.sim_agents(id),
  marked_by uuid REFERENCES public.users(id),
  spam_date date NOT NULL DEFAULT CURRENT_DATE,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- sim_deactivation_history
CREATE TABLE IF NOT EXISTS public.sim_deactivation_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sim_id uuid NOT NULL REFERENCES public.sim_master(id),
  deactivated_by uuid REFERENCES public.users(id),
  deactivated_date date NOT NULL DEFAULT CURRENT_DATE,
  reactivated_date date,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- sim_audit_log
CREATE TABLE IF NOT EXISTS public.sim_audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sim_id uuid REFERENCES public.sim_master(id),
  performed_by uuid REFERENCES public.users(id),
  action text NOT NULL,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- chrome_extension_users
CREATE TABLE IF NOT EXISTS public.chrome_extension_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- chrome_prospects
CREATE TABLE IF NOT EXISTS public.chrome_prospects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.chrome_extension_users(id),
  linkedin_url text NOT NULL,
  name text NOT NULL,
  company text,
  job_title text,
  location text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


-- ============================================================
-- STEP 3: ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_names ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispositions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrichment_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lusha_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rtne_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sim_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sim_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sim_spam_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sim_deactivation_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sim_audit_log ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- STEP 4: RLS POLICIES
-- ============================================================

-- prospects: all authenticated users can read
DROP POLICY IF EXISTS "Authenticated users can read prospects" ON public.prospects;
CREATE POLICY "Authenticated users can read prospects"
  ON public.prospects FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert prospects" ON public.prospects;
CREATE POLICY "Authenticated users can insert prospects"
  ON public.prospects FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update prospects" ON public.prospects;
CREATE POLICY "Authenticated users can update prospects"
  ON public.prospects FOR UPDATE TO authenticated USING (true);

-- users: authenticated users can read
DROP POLICY IF EXISTS "users_select" ON public.users;
CREATE POLICY "users_select" ON public.users FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "users_insert" ON public.users;
CREATE POLICY "users_insert" ON public.users FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "users_update" ON public.users;
CREATE POLICY "users_update" ON public.users FOR UPDATE TO authenticated USING (true);

-- user_profiles
DROP POLICY IF EXISTS "user_profiles_select" ON public.user_profiles;
CREATE POLICY "user_profiles_select" ON public.user_profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "user_profiles_insert" ON public.user_profiles;
CREATE POLICY "user_profiles_insert" ON public.user_profiles FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "user_profiles_update" ON public.user_profiles;
CREATE POLICY "user_profiles_update" ON public.user_profiles FOR UPDATE TO authenticated USING (true);

-- lusha_api_keys: authenticated
DROP POLICY IF EXISTS "lusha_keys_select" ON public.lusha_api_keys;
CREATE POLICY "lusha_keys_select" ON public.lusha_api_keys FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "lusha_keys_insert" ON public.lusha_api_keys;
CREATE POLICY "lusha_keys_insert" ON public.lusha_api_keys FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "lusha_keys_update" ON public.lusha_api_keys;
CREATE POLICY "lusha_keys_update" ON public.lusha_api_keys FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "lusha_keys_delete" ON public.lusha_api_keys;
CREATE POLICY "lusha_keys_delete" ON public.lusha_api_keys FOR DELETE TO authenticated USING (true);

-- dispositions
DROP POLICY IF EXISTS "dispositions_select" ON public.dispositions;
CREATE POLICY "dispositions_select" ON public.dispositions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "dispositions_insert" ON public.dispositions;
CREATE POLICY "dispositions_insert" ON public.dispositions FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "dispositions_update" ON public.dispositions;
CREATE POLICY "dispositions_update" ON public.dispositions FOR UPDATE TO authenticated USING (true);

-- project_names
DROP POLICY IF EXISTS "project_names_select" ON public.project_names;
CREATE POLICY "project_names_select" ON public.project_names FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "project_names_all" ON public.project_names;
CREATE POLICY "project_names_all" ON public.project_names FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- rtne_requests
DROP POLICY IF EXISTS "rtne_select" ON public.rtne_requests;
CREATE POLICY "rtne_select" ON public.rtne_requests FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "rtne_insert" ON public.rtne_requests;
CREATE POLICY "rtne_insert" ON public.rtne_requests FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "rtne_update" ON public.rtne_requests;
CREATE POLICY "rtne_update" ON public.rtne_requests FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "rtne_delete" ON public.rtne_requests;
CREATE POLICY "rtne_delete" ON public.rtne_requests FOR DELETE TO authenticated USING (true);

-- sim tables
DROP POLICY IF EXISTS "sim_agents_all" ON public.sim_agents;
CREATE POLICY "sim_agents_all" ON public.sim_agents FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "sim_master_all" ON public.sim_master;
CREATE POLICY "sim_master_all" ON public.sim_master FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "sim_spam_all" ON public.sim_spam_history;
CREATE POLICY "sim_spam_all" ON public.sim_spam_history FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "sim_deact_all" ON public.sim_deactivation_history;
CREATE POLICY "sim_deact_all" ON public.sim_deactivation_history FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "sim_audit_all" ON public.sim_audit_log;
CREATE POLICY "sim_audit_all" ON public.sim_audit_log FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- master_prospects, project_prospects
DROP POLICY IF EXISTS "master_prospects_all" ON public.master_prospects;
CREATE POLICY "master_prospects_all" ON public.master_prospects FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "project_prospects_all" ON public.project_prospects;
CREATE POLICY "project_prospects_all" ON public.project_prospects FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "projects_all" ON public.projects;
CREATE POLICY "projects_all" ON public.projects FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "project_users_all" ON public.project_users;
CREATE POLICY "project_users_all" ON public.project_users FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- notifications, audit, activity
DROP POLICY IF EXISTS "notifications_all" ON public.notifications;
CREATE POLICY "notifications_all" ON public.notifications FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "audit_logs_all" ON public.audit_logs;
CREATE POLICY "audit_logs_all" ON public.audit_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "activity_logs_all" ON public.activity_logs;
CREATE POLICY "activity_logs_all" ON public.activity_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "credits_log_all" ON public.credits_log;
CREATE POLICY "credits_log_all" ON public.credits_log FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "enrichment_jobs_all" ON public.enrichment_jobs;
CREATE POLICY "enrichment_jobs_all" ON public.enrichment_jobs FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ============================================================
-- STEP 5: HELPER FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_current_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT role FROM public.users WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.get_user_role_safe()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COALESCE((SELECT role FROM public.users WHERE id = auth.uid()), 'anonymous');
$$;

CREATE OR REPLACE FUNCTION public.is_admin_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid()
    AND role IN ('admin', 'sub_admin')
  );
$$;

CREATE OR REPLACE FUNCTION public.sync_user_profile()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.users (id, email, name, role, project_name)
  SELECT
    au.id,
    au.email,
    COALESCE(au.raw_user_meta_data->>'full_name', au.email),
    COALESCE(au.raw_user_meta_data->>'role', 'caller'),
    au.raw_user_meta_data->>'project_name'
  FROM auth.users au
  WHERE au.id = auth.uid()
  ON CONFLICT (id) DO NOTHING;
END;
$$;


-- ============================================================
-- STEP 6: DEFAULT DATA - ADMIN Project
-- ============================================================

INSERT INTO public.project_names (name, is_active)
VALUES ('ADMIN', true)
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- DONE!
-- ============================================================
-- Now go to Authentication > Users and manually create:
-- Email: prashantk@amplior.com
-- Password: PrashantADMIN@1234545
-- Then run the INSERT below (replace USER_ID with the actual UUID):
--
-- INSERT INTO public.users (id, email, name, role, project_name, status)
-- VALUES ('USER_ID', 'prashantk@amplior.com', 'Prashant Kumar', 'admin', 'ADMIN', 'active')
-- ON CONFLICT (id) DO UPDATE SET role='admin', project_name='ADMIN';
--
-- INSERT INTO public.user_profiles (id, email, full_name, role, project)
-- VALUES ('USER_ID', 'prashantk@amplior.com', 'Prashant Kumar', 'admin', 'ADMIN')
-- ON CONFLICT (id) DO UPDATE SET role='admin', project='ADMIN';
-- ============================================================
